### ISSUE TITLE
Documentation or usage examples

### ISSUE THREAD

**Issue by gnestor** [timbr-io/jupyter-react-js#4]
I like the idea here and I'd like to give it a try and/or help develop, but I need a usage example to get started!

**Comment by chelm** [comment]
@gnestor Awesome! I've been working a lot on top of this lib this week and will add some docs for sure! 

We've laid out a couple ideas for moving this forward too, and I'll try to add a section on the readme that lays out some ideas. For instance i think it'd be really cool to have the "manager" and "component" act more like react components themselves and then those components could be extended directly in place of normal react components (or something). 

I'll add the docs this week!

**Comment by gnestor** [comment]
@chelm Great! I've got some ideas too...like passing a lambda from Python to a React component via props so that when when a user slides a slider, the kernel _reacts_ to that event 😉

**Comment by chelm** [comment]
@gnestor Awesome idea! The current communication between python and js is handled via jupyter comms which use the existing websocket. Anyway, I made the docs much more complete in terms of usage and created and example usage repo here: 

https://github.com/timbr-io/jupyter-react-example

Check it out and let me know what think. We're doing a lot of work with this these days, hope you find it useful.

**Comment by gnestor** [comment]
@chelm Awesome! I cloned and installed the example project but unfortunately ran into an error:

![image](https://cloud.githubusercontent.com/assets/512354/19259666/8e850820-8f38-11e6-8b6f-7bbcb3da322c.png)

**Comment by chelm** [comment]
Ahhh looks like an issue with python 3.5 maybe not liking the imports on the Jupyter-React (Python) side. Let me see if I can repo that in a new env. It might just need to be told that its a relative import.

**Comment by chelm** [comment]
@gnestor Ok i've pushed up a wheel for python 3.5 for the jupyter-react module. I'm guessing you'll want to uninstall `jupyter-react` then re-run the `python setup.py develop` command. Also will need to do a git pull inside this repo. 

I'm not 100% certain this will fix it entirely but it is working in my 3.5 env now. I might be missing something though.

Thanks for helping me with this.

**Comment by chelm** [comment]
reopening until we're sure it works in every way

**Comment by gnestor** [comment]
@chelm I tried to uninstall using `git clean -xfd` and `pip uninstall jupyter-react`, pulled using `git pull --force` and reinstalled using `python setup.py develop`. I'm still getting the same error 🙁

**Comment by chelm** [comment]
Well shoot. Sorry about that. I'll figure this one out. This does seems to be more of an issue with Jupyter-React not being able to import `component`. I'll focus on that first.

**Comment by chelm** [comment]
@gnestor Can you send me the error you get with this command: `from jupyter_react import Component` ?

Also verify that `jupyter_react` is version 0.1.3?

**Comment by gnestor** [comment]
Ah, `jupyter-react` was still at 0.1.2!! I just `pip install jupyter-react --upgrade` and it worked! Nice work!!
